/**
 * Core Type Definitions: Ration Menu Management
 *
 * This file defines the domain types for ration entities.
 * These types are used across the application for type safety.
 *
 * @see ../data-model.md for detailed field descriptions
 */

/**
 * RationsType Enum
 *
 * Represents the seven categories of food aliments with Spanish display labels.
 * Each type maps to a corresponding design token color from the design system.
 *
 * Design Token Mapping:
 * - lacteal → category-lacteal (M3 Primary purple)
 * - cereals_flours_pulses_legumes_tubers → category-cereals-flours-pulses-legumes-tubers (M3 Secondary)
 * - fruits → category-fruits (M3 Tertiary orange)
 * - vegetables → category-vegetables (M3 custom green)
 * - oily_and_dry_fruit → category-oily-dry-fruits (M3 custom brown)
 * - drinks → category-drinks (M3 custom blue)
 * - others → category-others (M3 surface-variant gray)
 */
export enum RationsType {
  /** Dairy products (lácteos) */
  lacteal = "lácteos",

  /** Cereals, flours, pulses, legumes, and tubers */
  cereals_flours_pulses_legumes_tubers = "cereales, harinas, legumbres y tuberculos",

  /** Fruits (frutas) */
  fruits = "frutas",

  /** Vegetables (hortalizas) */
  vegetables = "hortalizas",

  /** Oily and dry fruits (frutas secas y grasa) */
  oily_and_dry_fruit = "frutas secas y grasa",

  /** Drinks/beverages (bebidas) */
  drinks = "bebidas",

  /** Other food items (otros) */
  others = "otros",
}

/**
 * Ration Entity
 *
 * Represents a food item with nutritional information for meal planning
 * and blood glucose management.
 *
 * @property {string} id - Unique identifier (UUID)
 * @property {RationsType} type - Category of food aliment
 * @property {string} name - Human-readable name of the food item (max 200 chars)
 * @property {number} gramsToCarbohydrate - Grams of food containing 10g of carbohydrates (must be > 0)
 * @property {number|undefined} bloodGlucoseIndex - Optional glycemic index value (0-100)
 * @property {number} weight - Weight of food portion in grams (must be > 0)
 * @property {number} rations - Calculated ration value (must be > 0)
 * @property {Date} createdAt - Timestamp of creation (for sorting newest first)
 *
 * @example
 * ```typescript
 * const ration: Ration = {
 *   id: "550e8400-e29b-41d4-a716-446655440000",
 *   type: RationsType.lacteal,
 *   name: "Leche desnatada",
 *   gramsToCarbohydrate: 200,
 *   bloodGlucoseIndex: 32,
 *   weight: 250,
 *   rations: 1.25,
 *   createdAt: new Date("2026-02-12T14:30:00.000Z")
 * };
 * ```
 */
export interface Ration {
  /**
   * Unique identifier for the ration
   * Format: UUID v4
   * Generated using crypto.randomUUID() or equivalent
   */
  id: string;

  /**
   * Category of food aliment
   * Must be one of the RationsType enum values
   */
  type: RationsType;

  /**
   * Human-readable name of the food item
   * Constraints:
   * - Non-empty (trimmed)
   * - Maximum 200 characters
   */
  name: string;

  /**
   * Grams of food containing 10g of carbohydrates (HC)
   * Constraints:
   * - Must be greater than 0
   * - Typically ranges from 5g to 500g
   */
  gramsToCarbohydrate: number;

  /**
   * Optional glycemic index value
   * Constraints:
   * - If provided, must be between 0 and 100
   * - undefined if not measured/known
   */
  bloodGlucoseIndex?: number;

  /**
   * Weight of food portion in grams
   * Constraints:
   * - Must be greater than 0
   * - Actual portion size being consumed
   */
  weight: number;

  /**
   * Calculated ration value
   * Formula: rations = (weight / gramsToCarbohydrate) * 10
   * Constraints:
   * - Must be greater than 0
   * - Represents carbohydrate portions
   */
  rations: number;

  /**
   * Timestamp of creation
   * Used for sorting (newest first) and display
   * Stored as ISO 8601 string in localStorage, deserialized to Date object
   */
  createdAt: Date;
}

/**
 * CreateRationDTO
 *
 * Data Transfer Object for creating new rations.
 * Similar to Ration but without id and createdAt (generated by system).
 */
export type CreateRationDTO = Omit<Ration, "id" | "createdAt">;

/**
 * UpdateRationDTO
 *
 * Data Transfer Object for updating existing rations.
 * All fields optional except id (partial update).
 */
export type UpdateRationDTO = Partial<Omit<Ration, "id" | "createdAt">> & {
  id: string;
};

/**
 * RationFilters
 *
 * Filtering options for querying rations (future use).
 */
export interface RationFilters {
  /** Filter by ration type(s) */
  types?: RationsType[];

  /** Filter by name (partial match, case-insensitive) */
  nameSearch?: string;

  /** Filter by date range */
  createdAfter?: Date;
  createdBefore?: Date;

  /** Filter by blood glucose index range */
  bloodGlucoseIndexMin?: number;
  bloodGlucoseIndexMax?: number;
}

/**
 * ValidationError
 *
 * Represents validation errors for form fields.
 */
export interface ValidationError {
  /** Field name that failed validation */
  field: keyof Ration;

  /** Human-readable error message */
  message: string;
}

/**
 * ValidationResult
 *
 * Result of validating a Ration or CreateRationDTO.
 */
export interface ValidationResult {
  /** Whether validation passed */
  valid: boolean;

  /** Map of field names to error messages (empty if valid) */
  errors: Record<string, string>;
}
