/**
 * Do not edit directly, this file was auto-generated.
 */

module.exports = {
  CategoryColorsCategoryLacteal: "#6750a4",
  CategoryColorsCategoryCerealsFloursPulsesLegumesTubers: "#625b71",
  CategoryColorsCategoryFruits: "#7d5260",
  CategoryColorsCategoryVegetables: "#386a20",
  CategoryColorsCategoryOilyDryFruits: "#6c5d3d",
  CategoryColorsCategoryDrinks: "#0061a4",
  CategoryColorsCategoryOthers: "#49454f",
  StateColorsStateOffline: "#bf360c",
  StateColorsStateSyncing: "#01579b",
  StateColorsStateSyncError: "#d32f2f",
  StateColorsStateOnline: "#1b5e20",
  FeedbackColorsFeedbackSuccess: "#2e7d32",
  FeedbackColorsFeedbackWarning: "#bf360c",
  FeedbackColorsFeedbackError: "#c62828",
  FeedbackColorsFeedbackInfo: "#0277bd",
  TypographyHeading1: {
    fontSize: "57px",
    lineHeight: "64px",
    letterSpacing: "-0.25px",
    fontWeight: 400,
    fontFamily: "'Roboto', sans-serif",
  },
  TypographyHeading2: {
    fontSize: "45px",
    lineHeight: "52px",
    letterSpacing: "0px",
    fontWeight: 400,
    fontFamily: "'Roboto', sans-serif",
  },
  TypographyHeading3: {
    fontSize: "36px",
    lineHeight: "44px",
    letterSpacing: "0px",
    fontWeight: 400,
    fontFamily: "'Roboto', sans-serif",
  },
  TypographyHeading4: {
    fontSize: "32px",
    lineHeight: "40px",
    letterSpacing: "0px",
    fontWeight: 400,
    fontFamily: "'Roboto', sans-serif",
  },
  TypographyHeading5: {
    fontSize: "28px",
    lineHeight: "36px",
    letterSpacing: "0px",
    fontWeight: 400,
    fontFamily: "'Roboto', sans-serif",
  },
  TypographyHeading6: {
    fontSize: "24px",
    lineHeight: "32px",
    letterSpacing: "0px",
    fontWeight: 400,
    fontFamily: "'Roboto', sans-serif",
  },
  TypographyBodyLarge: {
    fontSize: "16px",
    lineHeight: "24px",
    letterSpacing: "0.5px",
    fontWeight: 400,
    fontFamily: "'Roboto', sans-serif",
  },
  TypographyBodyMedium: {
    fontSize: "14px",
    lineHeight: "20px",
    letterSpacing: "0.25px",
    fontWeight: 400,
    fontFamily: "'Roboto', sans-serif",
  },
  TypographyBodySmall: {
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0.4px",
    fontWeight: 400,
    fontFamily: "'Roboto', sans-serif",
  },
  TypographyLabelLarge: {
    fontSize: "14px",
    lineHeight: "20px",
    letterSpacing: "0.1px",
    fontWeight: 500,
    fontFamily: "'Roboto', sans-serif",
  },
  TypographyLabelMedium: {
    fontSize: "12px",
    lineHeight: "16px",
    letterSpacing: "0.5px",
    fontWeight: 500,
    fontFamily: "'Roboto', sans-serif",
  },
  TypographyLabelSmall: {
    fontSize: "11px",
    lineHeight: "16px",
    letterSpacing: "0.5px",
    fontWeight: 500,
    fontFamily: "'Roboto', sans-serif",
  },
  SpacingSpace0: "0rem",
  SpacingSpace1: "0.5rem",
  SpacingSpace2: "1rem",
  SpacingSpace3: "1.5rem",
  SpacingSpace4: "2rem",
  SpacingSpace5: "2.5rem",
  SpacingSpace6: "3rem",
  SpacingSpace8: "4rem",
  SpacingSpace10: "5rem",
  SpacingSpace12: "6rem",
};
