import { Ration, CreateRationDTO } from "../models/Ration";

/**
 * RationRepository Interface
 *
 * Defines the contract for ration data persistence.
 * Implementations can use localStorage, IndexedDB, REST API, GraphQL, etc.
 *
 * The repository pattern provides:
 * - Abstraction over data source (implementation details hidden)
 * - Testability (easy to mock for unit tests)
 * - Flexibility (swap implementations without changing business logic)
 * - Single Responsibility (data access logic separated from components)
 *
 * @see ../../../specs/002-ration-menu-management/contracts/repository-interface.ts for detailed specification
 * @see ../../../specs/002-ration-menu-management/research.md for repository pattern best practices
 */
export interface RationRepository {
  /**
   * Save a new ration
   *
   * @param data - Ration data without id and createdAt (generated by repository)
   * @returns Promise resolving to the created ration with id and createdAt
   * @throws {Error} If save fails (e.g., localStorage quota exceeded)
   *
   * @example
   * ```typescript
   * const newRation = await repository.save({
   *   type: RationsType.fruits,
   *   name: "Manzana",
   *   gramsToCarbohydrate: 150,
   *   weight: 200,
   *   rations: 1.33
   * });
   * console.log(newRation.id); // "550e8400-e29b-41d4-a716-446655440000"
   * ```
   */
  save(data: CreateRationDTO): Promise<Ration>;

  /**
   * Find all rations
   *
   * @returns Promise resolving to array of all rations, sorted by createdAt DESC (newest first)
   * @throws {Error} If retrieval fails
   *
   * @example
   * ```typescript
   * const allRations = await repository.findAll();
   * console.log(allRations.length); // 42
   * ```
   */
  findAll(): Promise<Ration[]>;

  /**
   * Find ration by ID
   *
   * @param id - Unique identifier of the ration
   * @returns Promise resolving to the ration if found, null otherwise
   * @throws {Error} If retrieval fails
   *
   * @example
   * ```typescript
   * const ration = await repository.findById("550e8400-...");
   * if (ration) {
   *   console.log(ration.name); // "Manzana"
   * }
   * ```
   */
  findById(id: string): Promise<Ration | null>;

  /**
   * Delete a ration by ID
   *
   * @param id - Unique identifier of the ration to delete
   * @returns Promise resolving to true if deleted, false if not found
   * @throws {Error} If deletion fails
   *
   * @example
   * ```typescript
   * const deleted = await repository.delete("550e8400-...");
   * if (deleted) {
   *   console.log("Ration deleted successfully");
   * }
   * ```
   */
  delete(id: string): Promise<boolean>;
}
